### ISSUE TITLE
Inventory Headers

### ISSUE THREAD

**Issue by bbuchta** [zchristianl/corpse-test#1]
**Describe the bug**
Inventory headers are not properly aligned to columns

**Priority (Severity)**
Low

**To Reproduce**

Go to the Inventory tab.

**Expected behavior**

Headers should be properly aligned

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS Sierra
 - Browser: Safari
 - Version: 12.1.2

**Comment by bbuchta** [comment]
<img width="1151" alt="Screen Shot 2019-12-04 at 3 58 28 PM" src="https://user-images.githubusercontent.com/47580877/70185195-efb5a180-16ae-11ea-814a-bac5ba6a6978.png">

This appears to be an issue on all tables on my computer/browser.

**Comment by bbuchta** [comment]
<img width="1440" alt="Screen Shot 2019-12-04 at 3 02 59 PM" src="https://user-images.githubusercontent.com/47580877/70185270-0fe56080-16af-11ea-83b9-bc1c22406628.png">

Original bug screenshot

**Comment by zchristianl** [comment]
A fix has been created and will be released in a future version.
