### ISSUE TITLE
Ability To Make Seller Account

### ISSUE THREAD

**Issue by bbuchta** [zchristianl/corpse-test#10]
**Is your feature request related to a problem? Please describe.**
Currently we cannot make seller account through the developed UI. This would be a very useful feature so that sellers don't need to contact system admins to get started.

**Describe the solution you'd like**
I would like to see a drop down on the registration page to select account type.

**Describe alternatives you've considered**
You could also have a text field, but that would get annoying when there are only 2 possible options.

**Additional context**
This would also be helpful in finding more bugs in the system

**Comment by zchristianl** [comment]
The platform was made for one individual with 0 employees. We did not implement the functionality to add more sellers through the UI, (only through the back end (database)). Given time constraints, we do not intend to add this functionality. 

Moreover, Allowing the general public to freely register themselves as sellers and access customer data would be a high security risk.
