### ISSUE TITLE
Clients Cannot See Prices

### ISSUE THREAD

**Issue by bbuchta** [zchristianl/corpse-test#12]
**Is your feature request related to a problem? Please describe.**
Clients should be able to see the prices of the products and services listed by the seller when they are placing their order.

**Describe the solution you'd like**
I would like to see a field on the page be automatically populated with a price based on the current form input.

**Describe alternatives you've considered**
Alternatively, you could provide a pricing table, but client need to be able to see what they are going to be charged for things.

**Additional context**
It would be good to have this information on an order history page as well if that feature were added.

**Comment by zchristianl** [comment]
Our client does not have any pricing on their current website. She builds custom quotes for people based on their needs. Our platform always initially views an "order" as an estimate. Once an estimate is created, the seller contacts the client and they have the option to approve and progress the workflow of the order, or cancel it entirely.
