### ISSUE TITLE
Truncated Prices

### ISSUE THREAD

**Issue by nikolajreiser** [zchristianl/corpse-test#14]
**Describe the bug**
Cent amounts are truncated from price and cost when submitting or modifying an inventory item, despite the arrows in the cost and price fields adding cents to the price

**Priority (Severity)**
Low

**To Reproduce**
1. Go to create inventory item
2. Create item with a nonzero number of cents in the price and cost
3. Click submit 
4. Edit the submitted item
5. See that cent values have been truncated

**Comment by zchristianl** [comment]
This issue was previously fixed in another version of the platform.
