### ISSUE TITLE
valid email indicator when email is not valid

### ISSUE THREAD

**Issue by nikolajreiser** [zchristianl/corpse-test#15]
Description: when registering a client account, it is possible to enter an email (in the format of char@char) that is considered valid (a green checkmark appears) but when submit is clicked, "Invalid Email" appears at the top of the register page and all the fields are deleted, with no account being registered.

Valid email during account creation:
![Screen Shot 2019-12-06 at 8 10 58 PM](https://user-images.githubusercontent.com/19783966/70367328-998a5f00-1864-11ea-9656-97b7a09958f8.png)

After clicking submit:
![Screen Shot 2019-12-06 at 8 12 53 PM](https://user-images.githubusercontent.com/19783966/70367354-cd658480-1864-11ea-9766-017a0f62a891.png)

Severity: Medium

Suggestion: It looks like it's a problem with the email validation. Also, I would suggest removing the indicator at the top that says "Email is required" if the email is incorrect, since the checkmark next to the email field already serves this purpose. Lastly, all fields are deleted when submit is clicked, which is different behavior than what happens when there is other invalid information.

**Comment by zchristianl** [comment]
A fix has been created. This will be implemented in a future version.
