### ISSUE TITLE
Invalid Seller Credentials

### ISSUE THREAD

**Issue by nikolajreiser** [zchristianl/corpse-test#16]
Attempting to log in with seller credentials, as provided in the testing email from the CORPSE group, results in "Incorrect credentials" being displayed and no login occurs.

Severity: Critical

Note that this problem did not exist during previous tests, on earlier days, but started around 8:00 pm on Friday, the day testing is due. This change in program behavior suggests that CORPSE members are modifying their code throughout the testing period, which makes it difficult to consistently identify bugs and perform tests. Additionally, there are many features that are supposed to be part of the application under the seller account, and this prevents us from verifying that those features exist and work properly at this time.

**Comment by zchristianl** [comment]
The platform was updated & the database was initialized. Please try to login again.
