### ISSUE TITLE
No product gallery on home page

### ISSUE THREAD

**Issue by nikolajreiser** [zchristianl/corpse-test#17]
The home page (prior to login) does not contain a product gallery or link to a product gallery, contradicting the specifications of Home Page View [1] in the design and planning document.

Severity: Low

Suggestions: Either update the application to show a product gallery on the home page, or update the document and remove that specific view specification.

**Comment by zchristianl** [comment]
The document will be adjusted. We'll leave a link to her original website with the gallery instead.
