### ISSUE TITLE
Client can't create an order

### ISSUE THREAD

**Issue by nikolajreiser** [zchristianl/corpse-test#18]
When attempting to create an inquiry (by clicking "New Order" on the client home page), and filling out all the fields, there are no options in the Service field to select:

![Screen Shot 2019-12-06 at 8 56 58 PM](https://user-images.githubusercontent.com/19783966/70367935-f2f58c80-186a-11ea-9f81-641b4b698b6b.png)

This prevents the client from being able to submit an inquiry. 

Severity: High

This behavior was not previously present in this application on previous days. Because clients now can not create orders, this means that a major client feature is either missing, or in some way inaccessible for testing.

**Comment by zchristianl** [comment]
This is not a bug. This is because there are no inventory items. Because the database was recently initialized, you'll need to create a new inventory item and it will show up in the services list.
