### ISSUE TITLE
Create Invoice Hangs

### ISSUE THREAD

**Issue by bbuchta** [zchristianl/corpse-test#2]
**Describe the bug**
Clicking the "Create Invoice Download and Email" button on the dashboard hangs and never opens whatever should be opening. Eventually we get the error 504 Gateway Time-out.

**Priority (Severity)**
Critical

**To Reproduce**
1. Go to 'Dashboard'
2. Click on 'Create Invoice Download and Email'
3. Wait
4. Continue Waiting
5. See 504 Gateway Time-out error

**Expected behavior**
I would expect to "Create Invoice Download and Email"

**Desktop (please complete the following information):**
 - OS: MacOS Sierra 
 - Browser: Safari
 - Version: 12.1.2

**Comment by zchristianl** [comment]
I believe we initially had some trouble getting email to work with our AWS instance. This issue was fixed in later versions.
