### ISSUE TITLE
update password 

### ISSUE THREAD

**Issue by nikolajreiser** [zchristianl/corpse-test#20]
The change password feature in edit profile in a client account does not work properly. When a new password is entered, and update (the upper one, beneath the confirm password field) is clicked, success is indicated with the [sic] "You password has been changed!" However, logging in with that new password is unsuccessful (the message "Invalid username or password" is displayed) and logging in with the original password that was specified on account creation is still successful.

Severity: Medium

Also note that updating any of the information below password using the lower update, while functional, logs the user out of the account. Since updating the password does not log the user out, I am unsure if this behavior (logging the user out) is intended or not.

**Comment by zchristianl** [comment]
A fix has been implemented and will be released in a later version.
