### ISSUE TITLE
Not receiving forgot password email with instructions

### ISSUE THREAD

**Issue by rshih2** [zchristianl/corpse-test#3]
**Describe the bug**
Used real email for registering and tested forgot password. Did not receive email with further instructions.

**Priority (Severity)**
Low

**To Reproduce**
1. Register with real email
2. Click forgot password
3. Enter email

**Expected behavior**
Receive email with password reset instructions.
**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - Browser chrome
 - Version 78.0.3904.108

**Additional context**

**Comment by zchristianl** [comment]
I believe we initially had some trouble getting email to work with our AWS instance. This issue was fixed in later versions.
