### ISSUE TITLE
Stripe in testing mode w/ bad descriptors

### ISSUE THREAD

**Issue by bbuchta** [zchristianl/corpse-test#4]
**Describe the bug**
Stripe payment system was left in testing mode and has generic descriptors like "Sample Store"

**Priority (Severity)**
Medium

**To Reproduce**
1. Go to 'https://proteinctcorpse.com/payment/checkout'
2. Click on 'Checkout'
3. See testing mode with generic descriptors

**Expected behavior**
Descriptors should describe actual actions

**Desktop (please complete the following information):**
 - OS: MacOS Sierra
 - Browser: Safari
 - Version: 12.1.2

**Additional context**
It would make sense if this was left for us to test, but the descriptors should at least be accurate.

**Comment by zchristianl** [comment]
Stripe is still in testing mode because our platform has not yet reached production, and thus may not accept payments at this time. The descriptors were updated in a later version of the platform.
