### ISSUE TITLE
View Button in Orders Not Working

### ISSUE THREAD

**Issue by 7nafoaix** [zchristianl/corpse-test#5]
**Describe the bug**
Clicking View button on the order page causes a 504 Gateway time-out

**Priority (Severity)**
High

**To Reproduce**
1. Go to 'Orders'
2. Click on 'View'
3. Wait
4. See 504 Gateway Time-out error

**Expected behavior**
Clicking on the view button will lead to a page with detailed information about the order

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 78.0.3904.108 (Official Build) (64-bit)

**Comment by zchristianl** [comment]
I was able to view orders in both the local and remote instance of our platform. It is possible that an old older from prior testing had a null value in it, or that it may have been fixed in another version. Nonetheless, orders may be viewed.
