### ISSUE TITLE
Confirmation Emails Not Sending

### ISSUE THREAD

**Issue by bbuchta** [zchristianl/corpse-test#6]
**Describe the bug**
No confirmation email is received to my email after placing an inquiry and getting and notification saying a confirmation email has been sent.

**Priority (Severity)**
High

**To Reproduce**
1. Go to 'New Order'
2. Fill out the form
3. submit the form
4. See message saying confirmation has been sent
5. check email 
6. wait and check email again
7. finally accept that no email is coming 

**Expected behavior**
I would expect to receive an email

**Desktop (please complete the following information):**
 - OS: MacOS Sierra
 - Browser: Safari 
 - Version: 12.1.2

**Comment by zchristianl** [comment]
I believe we initially had some trouble getting email to work with our AWS instance. This issue was fixed in later versions.
