### ISSUE TITLE
Client Order Tracking

### ISSUE THREAD

**Issue by bbuchta** [zchristianl/corpse-test#7]
**Is your feature request related to a problem? Please describe.**
There is no way to see what orders I have placed as a customer. There is not even a confirmation email to go back to.

**Describe the solution you'd like**
I would like to see an orders tab that shows me the previous orders I have placed. 

**Describe alternatives you've considered**
If you cannot add an orders tab to the site, I would at least like to be able to refer to order details through confirmation emails.

**Additional context**
Having no way of referring back to what details I entered would bother me as a user.

**Comment by zchristianl** [comment]
Client order confirmation emails were fixed in another version. We are currently working on the client view so they may see all the orders they've placed.
