### ISSUE TITLE
View Button in Specific Client Not Functioning

### ISSUE THREAD

**Issue by 7nafoaix** [zchristianl/corpse-test#8]
**Describe the bug**
Clicking the View button on specific clients page to see the detail of the order is not working

**Priority (Severity)**
High

**To Reproduce**
1. Go to 'Clients'
2. Click on 'View'
3. Click on 'View'
4. Wait and finally get a 504 Gateway Time-out error

**Expected behavior**
See the details of this order from the client

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Browser: Google Chrome
 - Version: 78.0.3904.108 (Official Build) (64-bit)

**Comment by zchristianl** [comment]
It would have been nice to know which client & which order (if not all of them) were causing this issue specifically. Our clients may be identified by a number of attributes and orders may be identified by their order number. From my testing, the view buttons for clients & orders are operational. I cannot replicate the results; the issue must be closed.
