### ISSUE TITLE
Client Account Profile Page

### ISSUE THREAD

**Issue by bbuchta** [zchristianl/corpse-test#9]
**Is your feature request related to a problem? Please describe.**
There should be a way for the client to see at least some of there account information as well as edit it. Like what if a client moves? Right now they would need to contact customer support and have an admin change their address.

**Describe the solution you'd like**
I would like to see a profile viewer/editor similar to the seller's.

**Describe alternatives you've considered**
Alternatively, you could add a customer support contact, but users need to be able to access and edit this information.

**Comment by zchristianl** [comment]
In a later version, we released a view for clients to edit their personal information, such as their address.
